cd ..
python run.py \
    --input_seq_length 9 \
    --output_seq_length 3 \
    --dimension_3D 3 \
    --num_hidden 8,8,4 \
    --filter_size 10 \
    --lr 0.01 \
    --batch_size 10 \
    --max_iterations 50 \
    --is_training True \
    --save_dir checkpoints/ \
    --gen_frm_dir results/ \
    --train_data_paths data/milan_tra.npy \
    --valid_data_paths data/milan_val.npy \
    --test_data_paths data/milan_test.npy \
    --dataset_name milan \
    --img_width 100 \
    --model_name e3d_lstm \
    --layer_norm True \
    --scheduled_sampling True \
    --sampling_stop_iter 40 \
    --sampling_start_value 1.0 \
    --sampling_delta_per_iter 0.00002 \
    --display_interval 1 \
    --test_interval 5 \
    --snapshot_interval 5 \
    --allow_gpu_growth True
