cd ..
python run.py \
    --input_seq_length 6 \
    --output_seq_length 6 \
    --dimension_3D 2 \
    --num_hidden 10,10,10 \
    --filter_size 10 \
    --lr 0.01 \
    --batch_size 12 \
    --max_iterations 70000 \
    --is_training True \
    --save_dir checkpoints/6-6/10-10-10 \
    --gen_frm_dir results/6-6/10-10-10 \
    --train_data_paths data/milan_tra.npy \
    --valid_data_paths data/milan_val.npy \
    --test_data_paths data/milan_test.npy \
    --dataset_name milan \
    --img_width 100 \
    --model_name e3d_lstm \
    --layer_norm True \
    --scheduled_sampling True \
    --sampling_stop_iter 40 \
    --sampling_start_value 1.0 \
    --sampling_delta_per_iter 0.00002 \
    --display_interval 1 \
    --test_interval 1 \
    --snapshot_interval 1 \
    --allow_gpu_growth True
